import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { obtenerUsuario } from "../lib/auth";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const usuario = await obtenerUsuario();

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <header className="header">
          <div className="header-content">
            <Link href="/" className="home-button">🏠 Menú Principal</Link>
            {usuario && (
              <div className="user-info">
                Logueado como: {usuario.nombre} ({usuario.email})
                <Link href="/perfil" className="edit-profile-button">Editar Perfil</Link>
              </div>
            )}
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
